### ISSUE TITLE
missing calibration and camera_model yaml param not read

### ISSUE THREAD

**Issue by ghost** [ros-drivers/video_stream_opencv#100]
Hi,

I've used this node to publish RTSP to a ROS topic in order to calibrate the camera using ROS camera_calibrate node. Calibration generated the following yaml output below. However, upon loading this calibration file a warning is logged that it couldn't find the `distortion_model` parameter in the yaml, however that should be listed as `camera_model`, at least in ROS **melodic**.

Also, when camera_calibration writes the yaml output, this node has told it the incorrect height of 360. I filed a separate issue for this, but I've verified it still persists even if I launch this node with a dummy yaml config file (all distortion set to 1) with height config'd as 480 (the resulting calibration file still outputs 360)
```yaml
image_width: 640
image_height: 480  # this value incorrectly set to 360
camera_name: rugged_hd_ip
camera_matrix:
  rows: 3
  cols: 3
  data: [ 543.2134 ,    0.     ,  321.01119,
            0.     ,  543.06716,  190.99665,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob # this node expects "distortion_model"
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.480672, 0.184891, -0.001901, 0.002792, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 429.48141,    0.     ,  325.60516,    0.     ,
            0.     ,  512.12939,  191.97364,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
```

Without calibration:
![without_cal](https://user-images.githubusercontent.com/72039888/115904737-24a4ce80-a433-11eb-8108-a3b6dc2304bd.png)

With calibration (if I change `camera_model` to `distortion_model`):
```shell
roslaunch video_stream_opencv camera.launch video_stream_provider:=rtsp://192.168.1.1:554/h264 camera_info_url:='file:////root/git/adas/rugged_hd_ip_cal.yaml' width:=640 height:=480 camera_name:=rugged_hd_ip
```

![with_cal](https://user-images.githubusercontent.com/72039888/115904701-12c32b80-a433-11eb-9077-1ec4e35a2731.png)
